web/movie/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('search', views.search_view, name='search_view'),
    path('movie/<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('actor/<int:actor_id>/', views.actor_detail, name='actor_detail'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),
    
]

web/movie/models.py
from django.db import models

class Actor(models.Model):
    name = models.CharField(max_length=255)

class Movie(models.Model):
    title = models.CharField(max_length=255)
    link = models.URLField()
    actors = models.ManyToManyField(Actor)

web/movie/views.py
import hashlib
from django.shortcuts import render, get_object_or_404
from django.core.cache import cache
from .models import Movie, Actor

# In production we must create some utils files to avoid rewriting function in different apps
# but in our simple case i have put this here
def generate_cache_key(base, query):
    query_hash = hashlib.md5(query.encode()).hexdigest()
    return f"{base}_{query_hash}"


# About optimization
# I wrote simple function for that, but of coruse for 
# large data and better functionality in production we must use smth like elastic
# in that case we just use simple caching for 1 minute 
# In prodction i would do caching using Redis as example 
# Also PostgreSQL can provide caching for us, but in that case we using just Sqlite due to task requirements
# In production we also must implement pagination but it's not required by task
def search_view(request):
    query = request.GET.get('query', '')

    # We use hash keys for memcached safety 
    movie_key = generate_cache_key("movie", query)
    actor_key = generate_cache_key("actors", query)

    movies = cache.get(movie_key)
    if not movies:
        movies = Movie.objects.filter(title__icontains=query)
        cache.set(movie_key, movies, 60)

    actors = cache.get(actor_key)
    if not actors:
        actors = Actor.objects.filter(name__icontains=query)
        cache.set(actor_key, actors, 60)

    return render(request, 'search.html', {'movies': movies, 'actors': actors})


def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    return render(request, 'movie_detail.html', {'movie': movie})

def actor_detail(request, actor_id):
    actor = get_object_or_404(Actor, id=actor_id)
    return render(request, 'actor_detail.html', {'actor': actor})

web/movie/templates/actor_detail.html
<h1>{{ actor.name }}</h1>
<h3>Movies:</h3>
<ul>
{% for movie in actor.movie_set.all %}
    <li><a href="{% url 'movie_detail' movie.id %}">{{ movie.title }}</a></li>
{% endfor %}
</ul>

web/movie/templates/movie_detail.html
<h1>{{ movie.title }}</h1>
<h3>Actors:</h3>
<ul>
{% for actor in movie.actors.all %}
    <li><a href="{% url 'actor_detail' actor.id %}">{{ actor.name }}</a></li>
{% endfor %}
</ul>

web/movie/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSFD Search</title>
</head>
<body>

  <form method="get">
    <input type="text" name="query" placeholder="Search..." value="{{ request.GET.query }}">
    <button type="submit">Search</button>
  </form>

  <h2>Films</h2>
  {% for movie in movies %}
    <a href="{% url 'movie_detail' movie.id %}">{{ movie.title }}</a><br>
  {% endfor %}

  <h2>Actors</h2>
  {% for actor in actors %}
    <a href="{% url 'actor_detail' actor.id %}">{{ actor.name }}</a><br>
  {% endfor %}

</body>
</html>